site_name: Introduction to RNA-Seq - From quality control to pathway analysis

nav:
    - Home: index.md
    - Precourse preparations: precourse.md
    - Course schedule: course_schedule.md
    - Day1 :
        - Linux and cluster usage : days/linuxHPC.md
    - Day2 :
        - RNAseq - technologies and design : days/design.md
        - Server login + unix fresh up : days/server_login.md
        - Quality control : days/quality_control.md
        - Sequence trimming : days/trimming.md

    - Day3 :
        - Reads mapping : days/mapping.md
        - Read counting : days/counting.md

    - Day4 :
        - Differential Expression Inference : days/DE.md



# Repository
repo_name: WandrilleD/RNAseq-introduction-training
repo_url: https://github.com/WandrilleD/RNAseq-introduction-training
site_url: 

theme:
  name: material
  logo: assets/images/uni-basel-logo.svg
  favicon: assets/images/uni-basel-logo.svg

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - sane_lists
  - smarty
  - toc
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
